movieapp/urls.py
from .import views
from django.urls import path
app_name='movieapp'
urlpatterns = [
    path('', views.index,name='index'),
    path('movie/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]


if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieapp/forms.py
from  django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from .models import Movie
from.forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie

    }
    return render(request, "index.html",context)
def details(request,movie_id):
    movie=Movie.objects.get(id=movie_id)

    return render(request,"details.html",{'movie':movie})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter Your Movie Name"><br>
  <input type="text" name="desc" placeholder="Enter Your Movie Description"><br>
  <input type="text" name="year" placeholder="Enter Your Movie Year"><br>
  <input type="file" name="img"><br>
  <input type="submit">
</form>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body style="background-color:black;">
<h1 style="background-color:black;"></h1>
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST">
    {% csrf_token %}
    Are You Want To Delete This Movie ?
    <input type="submit">
</form>

templates/details.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300"><br>
        </div>

<div class="col-md-6">
    <h2>{{movie.name}}</h2>
    <h3>{{movie.desc}}</h3>
    <h6>{{movie.year}}</h6>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
</div>
    </div>
</div>

{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="Submit">
</form>

templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}>
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="200px;">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:details' i.id %}" class="btn btn-primary">Details</a><br>
  </div>
</div>

        </div>
        {% endfor %}
    </div>
</div>







{% endblock %}